import express from 'express';import cors from 'cors';import helmet from 'helmet';import {rateLimit} from 'express-rate-limit';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';import {existsSync} from 'node:fs';import {randomUUID} from 'node:crypto';
import {PolicySchema,SolverInputSchema,validateTimetable,type SolverResult} from '@chronos/domain';
import {collections,departments,faculty,resources,policies,runs,slots,solverInput,versions,buildSessions,type Entity} from './store.js';
import {ready,persistEntity,persistPolicy,persistGeneration,persistMove,persistTransition,audit,logAIAction,persistFacultyAvailability,persistResourceAvailability} from './db.js';
import {interpretWithProvider} from './llm.js';
import {authenticate,authorize,currentUser,login} from './auth.js';
import {createSchemas} from './setup-schemas.js';

const schedulerPath=fileURLToPath(new URL('../../../scheduler/solve.py',import.meta.url));
const localPython=fileURLToPath(new URL('../../../.venv/bin/python',import.meta.url));
function runScheduler(input:unknown):Promise<SolverResult>{return new Promise((resolve,reject)=>{const child=spawn(process.env.SCHEDULER_PYTHON??(existsSync(localPython)?localPython:'python3'),[schedulerPath],{stdio:['pipe','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',x=>stdout+=x);child.stderr.on('data',x=>stderr+=x);child.on('error',reject);child.on('close',code=>{try{resolve(JSON.parse(stdout));}catch{reject(new Error(`Scheduler exited ${code}: ${stderr||stdout}`));}});child.stdin.end(JSON.stringify(input));});}
export const app=express();app.disable('x-powered-by');app.use(helmet({crossOriginResourcePolicy:false,contentSecurityPolicy:false}));app.use(cors({origin:process.env.APP_ORIGIN?.split(',')??true,credentials:true}));app.use(express.json({limit:'1mb'}));const authLimit=rateLimit({windowMs:15*60_000,limit:30,standardHeaders:'draft-8',legacyHeaders:false});const operationLimit=rateLimit({windowMs:60_000,limit:30,standardHeaders:'draft-8',legacyHeaders:false});
app.get('/api/health',async(_req,res,next)=>{try{await ready;res.json({status:'ok',service:'chronos-api',database:'ready'});}catch(e){next(e);}});
app.post('/api/auth/login',authLimit,async(req,res,next)=>{try{const result=await login(String(req.body.email??''),String(req.body.password??''));if(!result)return res.status(401).json({error:{code:'INVALID_CREDENTIALS',message:'Email or password is incorrect'}});res.json(result);}catch(e){next(e);}});
app.use('/api',async(_req,_res,next)=>{try{await ready;next();}catch(e){next(e);}});app.use('/api',authenticate);
app.get('/api/session',(req,res)=>res.json({user:currentUser(req)}));
app.get('/api/dashboard',(_req,res)=>{const latest=versions.at(-1);res.json({academicYear:{id:'ay-26',name:'2026–27'},counts:{departments:departments.length,faculty:faculty.length,resources:resources.length,requirements:collections.requirements.length,sessions:buildSessions().length},latestVersion:latest??null,unresolvedConflicts:latest?.validation?.conflicts.length??0,latestRun:runs.at(-1)??null});});
app.get('/api/slots',(_req,res)=>res.json(slots));
app.get('/api/:collection',(req,res,next)=>{const data=collections[String(req.params.collection)];if(!data)return next();res.json(data);});
app.post('/api/:collection',authorize('ADMIN','HOD'),async(req,res,next)=>{const name=String(req.params.collection);const data=collections[name];if(!data)return next();if(!req.body||typeof req.body!=='object')return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'A JSON object is required'}});const schema=createSchemas[name];if(!schema)return res.status(405).json({error:{code:'UNSUPPORTED_CREATE',message:`Create is not available for ${name}`}});const parsed=schema.safeParse(req.body);if(!parsed.success)return res.status(422).json({error:{code:'VALIDATION_ERROR',message:'The submitted record is invalid',details:parsed.error.flatten()}});const entity={...parsed.data,id:parsed.data.id||randomUUID()} as Entity;if(data.some(x=>x.id===entity.id))return res.status(409).json({error:{code:'DUPLICATE',message:`${entity.id} already exists`}});try{await persistEntity(name,entity);data.push(entity);await audit(currentUser(req).id,'CREATE',name,entity.id,entity);res.status(201).json(entity);}catch(e){next(e);}});
app.put('/api/faculty/:id/availability',authorize('ADMIN','HOD'),async(req,res,next)=>{const f=faculty.find(x=>x.id===req.params.id);if(!f)return res.status(404).json({error:{code:'NOT_FOUND',message:'Faculty not found'}});const unavailable=Array.isArray(req.body.unavailableSlotIds)?req.body.unavailableSlotIds:[],preferred=Array.isArray(req.body.preferredSlotIds)?req.body.preferredSlotIds:[];if([...unavailable,...preferred].some(id=>!slots.some(s=>s.id===id)))return res.status(422).json({error:{code:'UNKNOWN_SLOT',message:'Availability contains an unknown time slot'}});try{await persistFacultyAvailability(f.id,unavailable,preferred);f.unavailableSlotIds=unavailable;f.preferredSlotIds=preferred;await audit(currentUser(req).id,'UPDATE_AVAILABILITY','Faculty',f.id,{unavailable,preferred});res.json(f);}catch(e){next(e);}});
app.put('/api/resources/:id/availability',authorize('ADMIN','HOD'),async(req,res,next)=>{const r=resources.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({error:{code:'NOT_FOUND',message:'Resource not found'}});const unavailable=Array.isArray(req.body.unavailableSlotIds)?req.body.unavailableSlotIds:[];if(unavailable.some((id:string)=>!slots.some(s=>s.id===id)))return res.status(422).json({error:{code:'UNKNOWN_SLOT',message:'Availability contains an unknown time slot'}});try{await persistResourceAvailability(r.id,unavailable);r.unavailableSlotIds=unavailable;await audit(currentUser(req).id,'UPDATE_AVAILABILITY','Resource',r.id,{unavailable});res.json(r);}catch(e){next(e);}});
app.post('/api/generation/preflight',authorize('ADMIN','HOD'),(_req,res)=>{const input=solverInput();const issues=[] as {code:string;message:string}[];if(!input.sessions.length)issues.push({code:'NO_SESSIONS',message:'No teaching requirements expand into sessions'});for(const s of input.sessions)if(!input.faculty.some(f=>f.id===s.facultyId))issues.push({code:'MISSING_FACULTY',message:`${s.title} has no valid faculty`});if(!input.slots.length)issues.push({code:'NO_TIME_PROFILE',message:'No enabled time slots exist'});if(!input.resources.length)issues.push({code:'NO_RESOURCES',message:'No active resources exist'});res.json({valid:!issues.length,issues,summary:{sessions:input.sessions.length,resources:input.resources.length,slots:input.slots.length}});});
app.post('/api/generation/run',operationLimit,authorize('ADMIN','HOD'),async(_req,res,next)=>{const run={id:randomUUID(),status:'SOLVING',startedAt:new Date().toISOString()} as (typeof runs)[number];runs.push(run);try{const input=SolverInputSchema.parse(solverInput());const result=await runScheduler(input);run.status=result.status;run.completedAt=new Date().toISOString();run.result=result;if(['OPTIMAL','FEASIBLE'].includes(result.status)){const report=validateTimetable(input,result.assignments);const version={id:randomUUID(),version:versions.length+1,status:(report.valid?'VALIDATED':'GENERATED') as 'VALIDATED'|'GENERATED',assignments:result.assignments,validation:report,createdAt:new Date().toISOString()};versions.push(version);await persistGeneration(run,version);await audit(currentUser(_req).id,'GENERATE','TimetableVersion',version.id,{runId:run.id,status:version.status});return res.status(201).json({run,version});}await persistGeneration(run);res.status(422).json({run});}catch(error){run.status='FAILED';run.completedAt=new Date().toISOString();next(error);}});
app.get('/api/generation/runs',(_req,res)=>res.json(runs));app.get('/api/timetables/versions',(_req,res)=>res.json(versions));
app.get('/api/timetables/versions/:id',(req,res)=>{const version=versions.find(v=>v.id===req.params.id);if(!version)return res.status(404).json({error:{code:'NOT_FOUND',message:'Timetable version not found'}});res.json({...version,sessions:buildSessions(),resources,faculty,divisions:collections.divisions,batches:collections.batches,slots});});
app.post('/api/timetables/versions/:id/move',authorize('ADMIN','HOD'),async(req,res,next)=>{const version=versions.find(v=>v.id===req.params.id);if(!version)return res.status(404).json({error:{code:'NOT_FOUND',message:'Version not found'}});if(version.status==='PUBLISHED')return res.status(409).json({error:{code:'PUBLISHED_IMMUTABLE',message:'Create a new version before editing a published timetable'}});const {sessionId,resourceId,slotIds}=req.body;const moved=version.assignments.map(a=>a.sessionId===sessionId?{...a,resourceId,slotIds,score:0}:a);if(!moved.some(a=>a.sessionId===sessionId))return res.status(404).json({error:{code:'SESSION_NOT_FOUND',message:'Session is not present in this version'}});const report=validateTimetable(solverInput(),moved);if(!report.valid)return res.status(422).json({error:{code:'INVALID_MOVE',message:'Move rejected because it violates hard constraints',conflicts:report.conflicts}});version.assignments=moved;version.validation=report;version.status='VALIDATED';try{await persistMove(version,sessionId);await audit(currentUser(req).id,'MANUAL_MOVE','TimetableEntry',sessionId,{resourceId,slotIds});res.json(version);}catch(e){next(e);}});
app.post('/api/timetables/versions/:id/transition',authorize('ADMIN','HOD'),async(req,res,next)=>{const v=versions.find(x=>x.id===req.params.id);if(!v)return res.status(404).json({error:{code:'NOT_FOUND',message:'Version not found'}});const nextStatus=String(req.body.status);const allowed:Record<string,string[]>= {DRAFT:['GENERATED'],GENERATED:['VALIDATED'],VALIDATED:['REVIEWED'],REVIEWED:['APPROVED'],APPROVED:['PUBLISHED']};if(!allowed[v.status]?.includes(nextStatus))return res.status(409).json({error:{code:'INVALID_TRANSITION',message:`Cannot transition ${v.status} to ${nextStatus}`}});if(nextStatus==='PUBLISHED'&&!v.validation?.valid)return res.status(409).json({error:{code:'VALIDATION_REQUIRED',message:'Only independently validated versions can be published'}});v.status=nextStatus as typeof v.status;try{await persistTransition(v.id,nextStatus);await audit(currentUser(req).id,'TRANSITION','TimetableVersion',v.id,{status:nextStatus});res.json(v);}catch(e){next(e);}});

function parseCsvLine(line:string){const values:string[]=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){values.push(value.trim());value='';}else value+=c;}values.push(value.trim());return values;}
const pendingImports=new Map<string,{collection:string;rows:Entity[]}>();
app.post('/api/import/preview',authorize('ADMIN','HOD'),(req,res)=>{const collection=String(req.body.collection??''),schema=createSchemas[collection],target=collections[collection];if(!schema||!target)return res.status(400).json({error:{code:'UNSUPPORTED_IMPORT',message:'Choose a supported configuration collection'}});let source=req.body.rows;if(!source&&typeof req.body.csv==='string'){const lines=req.body.csv.trim().split(/\r?\n/),headers=parseCsvLine(lines.shift()??'');source=lines.map((line:string)=>{const values=parseCsvLine(line),row:any=Object.fromEntries(values.map((x:string,i:number)=>[headers[i],x]));for(const key of ['capabilities','requiredCapabilities','preferredCapabilities','unavailableSlotIds'])if(typeof row[key]==='string')row[key]=row[key].split(/[;,]/).map((x:string)=>x.trim()).filter(Boolean);return row;});}if(!Array.isArray(source))return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'rows or csv is required'}});const valid:Entity[]=[],errors:any[]=[];source.forEach((row:any,index:number)=>{const parsed=schema.safeParse(row);if(!parsed.success)errors.push({row:index+1,issues:parsed.error.issues.map(x=>({path:x.path.join('.'),message:x.message}))});else{const e={...parsed.data,id:parsed.data.id||randomUUID()} as Entity;if(target.some(x=>x.id===e.id)||valid.some(x=>x.id===e.id))errors.push({row:index+1,issues:[{path:'id',message:'Duplicate identifier'}]});else valid.push(e);}});const token=randomUUID();if(!errors.length)pendingImports.set(token,{collection,rows:valid});res.json({valid:!errors.length,token:errors.length?null:token,collection,totalRows:source.length,validRows:valid,errors});});
app.post('/api/import/:token/confirm',authorize('ADMIN','HOD'),async(req,res,next)=>{const pendingImport=pendingImports.get(String(req.params.token));if(!pendingImport)return res.status(404).json({error:{code:'IMPORT_NOT_FOUND',message:'Import preview expired or had validation errors'}});try{for(const row of pendingImport.rows){await persistEntity(pendingImport.collection,row);collections[pendingImport.collection].push(row);}pendingImports.delete(String(req.params.token));await audit(currentUser(req).id,'IMPORT',pendingImport.collection,null,{count:pendingImport.rows.length});res.status(201).json({imported:pendingImport.rows.length,collection:pendingImport.collection});}catch(e){next(e);}});
const pending=new Map<string,{policy:unknown;summary:string}>();
app.post('/api/ai/interpret',operationLimit,authorize('ADMIN','HOD'),async(req,res,next)=>{try{const message=String(req.body.message??'').trim();if(!message)return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'message is required'}});const provider=await interpretWithProvider(message,resources,departments);let mentioned=provider?resources.filter(r=>provider.resourceIds.includes(r.id)):resources.filter(r=>message.toLowerCase().includes(r.name.toLowerCase())||message.toLowerCase().includes(r.id.toLowerCase()));const asksResource=/lab|room|classroom|workshop|resource/i.test(message);if(provider?.action==='CLARIFY'||(asksResource&&!mentioned.length)){const result={type:'clarification',message:provider?.clarification??'I could not match that resource to configured data. Which resource do you mean?',options:resources.map(r=>({id:r.id,name:r.name,type:r.type}))};await logAIAction(currentUser(req).id,'clarifyPolicy',{message},result);return res.json(result);}const dept=provider?.departmentId?departments.find(d=>d.id===provider.departmentId):departments.find(d=>message.toLowerCase().includes(String(d.name).toLowerCase())||message.toLowerCase().includes(String(d.code).toLowerCase()));const prohibit=provider?provider.action==='PROHIBIT_RESOURCE':/don.?t|do not|never|prohibit|prevent|cannot use/i.test(message);const prefer=provider?provider.action==='PREFER_RESOURCE':/prefer|priority|should use/i.test(message);if(mentioned.length&&(prohibit||prefer)){const policy={id:randomUUID(),name:prohibit?`Restrict ${mentioned[0].name}`:`Prefer ${mentioned[0].name}`,description:`Proposed from administrator instruction: ${message}`,type:prohibit?'RESOURCE_PROHIBITION':'RESOURCE_PREFERENCE',strength:prohibit?'HARD':'SOFT',weight:10,scope:dept?{departmentId:dept.id}:{},parameters:{[prohibit?'resourceIds':'preferredResourceIds']:mentioned.map(r=>r.id)},active:true,version:1};const id=randomUUID(),summary=`${prohibit?'Prevent':'Prefer'} ${mentioned.map(r=>r.name).join(', ')}${dept?` for ${dept.name}`:''}. This changes future scheduling behavior.`;pending.set(id,{policy,summary});const result={type:'confirmation',proposalId:id,summary,policy};await logAIAction(currentUser(req).id,'proposePolicy',{message},result,'AWAITING_CONFIRMATION');return res.json(result);}const result={type:'clarification',message:'Please state a configured resource and whether to prefer or prohibit it.',options:resources.map(r=>r.name)};await logAIAction(currentUser(req).id,'clarifyPolicy',{message},result);res.json(result);}catch(e){next(e);}});
app.post('/api/ai/proposals/:id/confirm',authorize('ADMIN','HOD'),async(req,res,next)=>{const proposal=pending.get(String(req.params.id));if(!proposal)return res.status(404).json({error:{code:'PROPOSAL_NOT_FOUND',message:'Proposal expired or does not exist'}});const parsed=PolicySchema.safeParse(proposal.policy);if(!parsed.success)return res.status(422).json({error:{code:'INVALID_POLICY',message:'The structured policy failed validation',details:parsed.error.flatten()}});try{await persistPolicy(parsed.data);policies.push(parsed.data);pending.delete(String(req.params.id));await audit(currentUser(req).id,'AI_CREATE_POLICY','SchedulingPolicy',parsed.data.id,parsed.data);res.status(201).json({tool:'createPolicy',result:parsed.data});}catch(e){next(e);}});
app.get('/api/timetables/versions/:id/export.csv',(req,res)=>{const v=versions.find(x=>x.id===req.params.id);if(!v)return res.status(404).json({error:{code:'NOT_FOUND',message:'Version not found'}});const sessions=buildSessions();const esc=(x:unknown)=>`"${String(x??'').replaceAll('\"','\"\"')}"`;const rows=[['Subject','Session','Faculty','Resource','Day','Start','End','Cohorts']];for(const a of v.assignments){const session=sessions.find(x=>x.id===a.sessionId)!;const resource=resources.find(x=>x.id===a.resourceId)!;const atomic=a.slotIds.map(id=>slots.find(x=>x.id===id)!).filter(Boolean);rows.push([session.subjectCode,session.title,faculty.find(x=>x.id===session.facultyId)?.name??session.facultyId,resource.name,atomic[0]?.label.split(' ')[0]??'',atomic[0]?.start??'',atomic.at(-1)?.end??'',session.cohortAtomIds.join('+')]);}res.setHeader('Content-Type','text/csv');res.setHeader('Content-Disposition',`attachment; filename=chronos-version-${v.version}.csv`);res.send(rows.map(row=>row.map(esc).join(',')).join('\n'));});
app.post('/api/ai/explain',(req,res)=>{const {versionId,sessionId}=req.body;const v=versions.find(x=>x.id===versionId);const a=v?.assignments.find(x=>x.sessionId===sessionId);const s=buildSessions().find(x=>x.id===sessionId);const r=resources.find(x=>x.id===a?.resourceId);if(!v||!a||!s||!r)return res.status(404).json({error:{code:'NOT_FOUND',message:'Assignment evidence was not found'}});const own=r.departmentId===s.preferredDepartmentId;res.json({explanation:`${s.title} was assigned to ${r.name}. It satisfies type ${s.resourceType}, capacity ${s.participantCount} (room: ${r.capacity}), and all required capabilities. ${own?'It is a preferred department resource.':'It is an eligible fallback; the department resource could not improve the globally feasible objective.'}`,evidence:{assignment:a,requiredCapabilities:s.requiredCapabilities,resourceCapabilities:r.capabilities,capacity:{required:s.participantCount,actual:r.capacity},policyIds:policies.filter(p=>p.active).map(p=>p.id)}});});
app.use((_req,res)=>res.status(404).json({error:{code:'NOT_FOUND',message:'Route not found'}}));
app.use((error:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{console.error(error);res.status(500).json({error:{code:'INTERNAL_ERROR',message:error instanceof Error?error.message:'Unexpected server error'}});});
