import {beforeEach,describe,expect,it} from 'vitest';import request from 'supertest';import {app} from './app.js';import {policies,runs,versions} from './store.js';
const auth={Authorization:'Bearer demo-admin'};
describe('Chronos API integration',()=>{
 beforeEach(()=>{versions.length=0;runs.length=0});
 it('authenticates a persisted user with a hashed password',async()=>{const r=await request(app).post('/api/auth/login').send({email:'admin@chronos.local',password:'Chronos123!'}).expect(200);expect(r.body.user.role).toBe('ADMIN');expect(r.body.token.split('.')).toHaveLength(3)});
 it('reports real dashboard counts',async()=>{const r=await request(app).get('/api/dashboard').set(auth).expect(200);expect(r.body.counts.sessions).toBeGreaterThan(0);expect(r.body.counts.resources).toBeGreaterThan(0)});
 it('generates, validates, persists and guards manual editing',async()=>{const r=await request(app).post('/api/generation/run').set(auth).expect(201);expect(r.body.run.result.status).toMatch(/OPTIMAL|FEASIBLE/);expect(r.body.version.validation.valid).toBe(true);expect(r.body.version.assignments).toHaveLength(r.body.run.result.metrics.sessions);const [first,second]=r.body.version.assignments;await request(app).post(`/api/timetables/versions/${r.body.version.id}/move`).set(auth).send(first).expect(200);const invalid=await request(app).post(`/api/timetables/versions/${r.body.version.id}/move`).set(auth).send({sessionId:second.sessionId,resourceId:first.resourceId,slotIds:first.slotIds}).expect(422);expect(invalid.body.error.conflicts.length).toBeGreaterThan(0)});
 it('rejects mutation for student role',()=>request(app).post('/api/resources').set({Authorization:'Bearer demo-student'}).send({name:'Unsafe'}).expect(403));
 it('validates setup writes rather than inserting incomplete records',async()=>{const r=await request(app).post('/api/resources').set(auth).send({name:'Broken lab'}).expect(422);expect(r.body.error.code).toBe('VALIDATION_ERROR')});
 it('persists faculty availability used by candidate generation',async()=>{const r=await request(app).put('/api/faculty/fac-meena/availability').set(auth).send({unavailableSlotIds:['mon-1'],preferredSlotIds:['mon-2']}).expect(200);expect(r.body.unavailableSlotIds).toContain('mon-1')});
 it('validates and stores student enrollment',async()=>{const r=await request(app).post('/api/enrollments').set(auth).send({rollNumber:'IT-E2E-01',studentName:'Test Student',divisionId:'div-a',batchId:'batch-a1'}).expect(201);expect(r.body.rollNumber).toBe('IT-E2E-01')});
 it('previews and confirms imports before writing',async()=>{const preview=await request(app).post('/api/import/preview').set(auth).send({collection:'resources',rows:[{code:'TEST-LAB',name:'Test Lab',type:'LAB',capacity:30,departmentId:'dept-it',capabilities:['Computers']}]}).expect(200);expect(preview.body.valid).toBe(true);const result=await request(app).post(`/api/import/${preview.body.token}/confirm`).set(auth).send({}).expect(201);expect(result.body.imported).toBe(1)});
 it('does not invent AI entities',async()=>{const r=await request(app).post('/api/ai/interpret').set(auth).send({message:'Use the Quantum Lab'}).expect(200);expect(r.body.type).toBe('clarification');expect(r.body.options.length).toBeGreaterThan(0)});
 it('requires confirmation then invokes typed createPolicy',async()=>{const before=policies.length;const proposal=await request(app).post('/api/ai/interpret').set(auth).send({message:"Don't use CSE AI Lab for Information Technology"}).expect(200);expect(proposal.body.type).toBe('confirmation');const result=await request(app).post(`/api/ai/proposals/${proposal.body.proposalId}/confirm`).set(auth).expect(201);expect(result.body.tool).toBe('createPolicy');expect(policies).toHaveLength(before+1)});
});
