import express from 'express';import cors from 'cors';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';import {existsSync} from 'node:fs';import {randomUUID} from 'node:crypto';
import {PolicySchema,SolverInputSchema,validateTimetable,type SolverResult} from '@chronos/domain';
import {collections,departments,faculty,resources,policies,runs,slots,solverInput,versions,buildSessions,type Entity} from './store.js';

const schedulerPath=fileURLToPath(new URL('../../../scheduler/solve.py',import.meta.url));
const localPython=fileURLToPath(new URL('../../../.venv/bin/python',import.meta.url));
function runScheduler(input:unknown):Promise<SolverResult>{return new Promise((resolve,reject)=>{const child=spawn(process.env.SCHEDULER_PYTHON??(existsSync(localPython)?localPython:'python3'),[schedulerPath],{stdio:['pipe','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',x=>stdout+=x);child.stderr.on('data',x=>stderr+=x);child.on('error',reject);child.on('close',code=>{try{resolve(JSON.parse(stdout));}catch{reject(new Error(`Scheduler exited ${code}: ${stderr||stdout}`));}});child.stdin.end(JSON.stringify(input));});}
function role(req:express.Request){const token=req.header('authorization')?.replace(/^Bearer\s+/i,'');return token==='demo-faculty'?'FACULTY':token==='demo-student'?'STUDENT':token==='demo-hod'?'HOD':'ADMIN';}
function admin(req:express.Request,res:express.Response,next:express.NextFunction){if(!['ADMIN','HOD'].includes(role(req)))return res.status(403).json({error:{code:'FORBIDDEN',message:'This action requires ADMIN or HOD permission'}});next();}
export const app=express();app.use(cors());app.use(express.json({limit:'1mb'}));
app.get('/api/health',(_req,res)=>res.json({status:'ok',service:'chronos-api'}));
app.get('/api/session',(req,res)=>res.json({user:{id:'demo',name:'Demo Administrator',role:role(req)}}));
app.get('/api/dashboard',(_req,res)=>{const latest=versions.at(-1);res.json({academicYear:{id:'ay-26',name:'2026–27'},counts:{departments:departments.length,faculty:faculty.length,resources:resources.length,requirements:collections.requirements.length,sessions:buildSessions().length},latestVersion:latest??null,unresolvedConflicts:latest?.validation?.conflicts.length??0,latestRun:runs.at(-1)??null});});
app.get('/api/slots',(_req,res)=>res.json(slots));
app.get('/api/:collection',(req,res,next)=>{const data=collections[String(req.params.collection)];if(!data)return next();res.json(data);});
app.post('/api/:collection',admin,(req,res,next)=>{const data=collections[String(req.params.collection)];if(!data)return next();if(!req.body||typeof req.body!=='object')return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'A JSON object is required'}});const entity={...req.body,id:req.body.id||randomUUID()} as Entity;if(data.some(x=>x.id===entity.id))return res.status(409).json({error:{code:'DUPLICATE',message:`${entity.id} already exists`}});data.push(entity);res.status(201).json(entity);});
app.post('/api/generation/preflight',admin,(_req,res)=>{const input=solverInput();const issues=[] as {code:string;message:string}[];if(!input.sessions.length)issues.push({code:'NO_SESSIONS',message:'No teaching requirements expand into sessions'});for(const s of input.sessions)if(!input.faculty.some(f=>f.id===s.facultyId))issues.push({code:'MISSING_FACULTY',message:`${s.title} has no valid faculty`});if(!input.slots.length)issues.push({code:'NO_TIME_PROFILE',message:'No enabled time slots exist'});if(!input.resources.length)issues.push({code:'NO_RESOURCES',message:'No active resources exist'});res.json({valid:!issues.length,issues,summary:{sessions:input.sessions.length,resources:input.resources.length,slots:input.slots.length}});});
app.post('/api/generation/run',admin,async(_req,res,next)=>{const run={id:randomUUID(),status:'SOLVING',startedAt:new Date().toISOString()} as (typeof runs)[number];runs.push(run);try{const input=SolverInputSchema.parse(solverInput());const result=await runScheduler(input);run.status=result.status;run.completedAt=new Date().toISOString();run.result=result;if(['OPTIMAL','FEASIBLE'].includes(result.status)){const report=validateTimetable(input,result.assignments);const version={id:randomUUID(),version:versions.length+1,status:(report.valid?'VALIDATED':'GENERATED') as 'VALIDATED'|'GENERATED',assignments:result.assignments,validation:report,createdAt:new Date().toISOString()};versions.push(version);return res.status(201).json({run,version});}res.status(422).json({run});}catch(error){run.status='FAILED';run.completedAt=new Date().toISOString();next(error);}});
app.get('/api/generation/runs',(_req,res)=>res.json(runs));app.get('/api/timetables/versions',(_req,res)=>res.json(versions));
app.get('/api/timetables/versions/:id',(req,res)=>{const version=versions.find(v=>v.id===req.params.id);if(!version)return res.status(404).json({error:{code:'NOT_FOUND',message:'Timetable version not found'}});res.json({...version,sessions:buildSessions(),resources,slots});});
app.post('/api/timetables/versions/:id/move',admin,(req,res)=>{const version=versions.find(v=>v.id===req.params.id);if(!version)return res.status(404).json({error:{code:'NOT_FOUND',message:'Version not found'}});if(version.status==='PUBLISHED')return res.status(409).json({error:{code:'PUBLISHED_IMMUTABLE',message:'Create a new version before editing a published timetable'}});const {sessionId,resourceId,slotIds}=req.body;const moved=version.assignments.map(a=>a.sessionId===sessionId?{...a,resourceId,slotIds,score:0}:a);if(!moved.some(a=>a.sessionId===sessionId))return res.status(404).json({error:{code:'SESSION_NOT_FOUND',message:'Session is not present in this version'}});const report=validateTimetable(solverInput(),moved);if(!report.valid)return res.status(422).json({error:{code:'INVALID_MOVE',message:'Move rejected because it violates hard constraints',conflicts:report.conflicts}});version.assignments=moved;version.validation=report;version.status='VALIDATED';res.json(version);});
app.post('/api/timetables/versions/:id/transition',admin,(req,res)=>{const v=versions.find(x=>x.id===req.params.id);if(!v)return res.status(404).json({error:{code:'NOT_FOUND',message:'Version not found'}});const next=String(req.body.status);const allowed:Record<string,string[]>= {DRAFT:['GENERATED'],GENERATED:['VALIDATED'],VALIDATED:['REVIEWED'],REVIEWED:['APPROVED'],APPROVED:['PUBLISHED']};if(!allowed[v.status]?.includes(next))return res.status(409).json({error:{code:'INVALID_TRANSITION',message:`Cannot transition ${v.status} to ${next}`}});if(next==='PUBLISHED'&&!v.validation?.valid)return res.status(409).json({error:{code:'VALIDATION_REQUIRED',message:'Only independently validated versions can be published'}});v.status=next as typeof v.status;res.json(v);});

const pending=new Map<string,{policy:unknown;summary:string}>();
app.post('/api/ai/interpret',admin,(req,res)=>{const message=String(req.body.message??'').trim();if(!message)return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'message is required'}});const mentionedResources=resources.filter(r=>message.toLocaleLowerCase().includes(r.name.toLocaleLowerCase())||message.toLocaleLowerCase().includes(r.id.toLocaleLowerCase()));const asksResource=/lab|room|classroom|workshop|resource/i.test(message);if(asksResource&&!mentionedResources.length){return res.json({type:'clarification',message:'I could not match that resource to configured data. Which resource do you mean?',options:resources.map(r=>({id:r.id,name:r.name,type:r.type}))});}const dept=departments.find(d=>message.toLocaleLowerCase().includes(String(d.name).toLocaleLowerCase())||message.toLocaleLowerCase().includes(String(d.code).toLocaleLowerCase()));const prohibit=/don.?t|do not|never|prohibit|prevent|cannot use/i.test(message);const prefer=/prefer|priority|should use/i.test(message);if(mentionedResources.length&&(prohibit||prefer)){const policy={id:randomUUID(),name:prohibit?`Restrict ${mentionedResources[0].name}`:`Prefer ${mentionedResources[0].name}`,description:`Proposed from administrator instruction: ${message}`,type:prohibit?'RESOURCE_PROHIBITION':'RESOURCE_PREFERENCE',strength:prohibit?'HARD':'SOFT',weight:10,scope:dept?{departmentId:dept.id}:{},parameters:{[prohibit?'resourceIds':'preferredResourceIds']:mentionedResources.map(r=>r.id)},active:true,version:1};const id=randomUUID();pending.set(id,{policy,summary:`${prohibit?'Prevent':'Prefer'} ${mentionedResources.map(r=>r.name).join(', ')}${dept?` for ${dept.name}`:''}. This changes future scheduling behavior.`});return res.json({type:'confirmation',proposalId:id,summary:pending.get(id)!.summary,policy});}return res.json({type:'clarification',message:'I can safely create resource preference or prohibition policies. Please state the configured resource and intended scope.',options:resources.map(r=>r.name)});});
app.post('/api/ai/proposals/:id/confirm',admin,(req,res)=>{const proposal=pending.get(String(req.params.id));if(!proposal)return res.status(404).json({error:{code:'PROPOSAL_NOT_FOUND',message:'Proposal expired or does not exist'}});const parsed=PolicySchema.safeParse(proposal.policy);if(!parsed.success)return res.status(422).json({error:{code:'INVALID_POLICY',message:'The structured policy failed validation',details:parsed.error.flatten()}});policies.push(parsed.data);pending.delete(String(req.params.id));res.status(201).json({tool:'createPolicy',result:parsed.data});});
app.post('/api/ai/explain',(req,res)=>{const {versionId,sessionId}=req.body;const v=versions.find(x=>x.id===versionId);const a=v?.assignments.find(x=>x.sessionId===sessionId);const s=buildSessions().find(x=>x.id===sessionId);const r=resources.find(x=>x.id===a?.resourceId);if(!v||!a||!s||!r)return res.status(404).json({error:{code:'NOT_FOUND',message:'Assignment evidence was not found'}});const own=r.departmentId===s.preferredDepartmentId;res.json({explanation:`${s.title} was assigned to ${r.name}. It satisfies type ${s.resourceType}, capacity ${s.participantCount} (room: ${r.capacity}), and all required capabilities. ${own?'It is a preferred department resource.':'It is an eligible fallback; the department resource could not improve the globally feasible objective.'}`,evidence:{assignment:a,requiredCapabilities:s.requiredCapabilities,resourceCapabilities:r.capabilities,capacity:{required:s.participantCount,actual:r.capacity},policyIds:policies.filter(p=>p.active).map(p=>p.id)}});});
app.use((_req,res)=>res.status(404).json({error:{code:'NOT_FOUND',message:'Route not found'}}));
app.use((error:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{console.error(error);res.status(500).json({error:{code:'INTERNAL_ERROR',message:error instanceof Error?error.message:'Unexpected server error'}});});
