import type {Request,Response,NextFunction} from 'express';
import {SignJWT,jwtVerify} from 'jose';
import {compare} from 'bcryptjs';
import {db,ready} from './db.js';
export type AuthUser={id:string;name:string;email:string;role:'ADMIN'|'HOD'|'FACULTY'|'STUDENT';departmentId?:string};
const secretText=process.env.JWT_SECRET??'development-only-change-me-before-production';if(process.env.NODE_ENV==='production'&&!process.env.JWT_SECRET)throw new Error('JWT_SECRET is required in production');const secret=new TextEncoder().encode(secretText);
export async function login(email:string,password:string){await ready;const result=await db.query<AuthUser&{passwordHash:string}>(`SELECT "id","name","email","role","departmentId","passwordHash" FROM "User" WHERE lower("email")=lower($1)`,[email]);const user=result.rows[0];if(!user?.passwordHash||!await compare(password,user.passwordHash))return null;const token=await new SignJWT({name:user.name,role:user.role,departmentId:user.departmentId}).setProtectedHeader({alg:'HS256'}).setSubject(user.id).setIssuedAt().setExpirationTime('8h').sign(secret);return {token,user:{id:user.id,name:user.name,email:user.email,role:user.role,departmentId:user.departmentId}};}
export async function authenticate(req:Request,res:Response,next:NextFunction){const raw=req.header('authorization')?.replace(/^Bearer\s+/i,'');if(!raw)return res.status(401).json({error:{code:'UNAUTHENTICATED',message:'A bearer token is required'}});if(process.env.NODE_ENV!=='production'&&raw.startsWith('demo-')){const role=raw==='demo-student'?'STUDENT':raw==='demo-faculty'?'FACULTY':raw==='demo-hod'?'HOD':'ADMIN';(req as Request&{user:AuthUser}).user={id:role==='STUDENT'?'user-student':'user-admin',name:`Demo ${role}`,email:`${role.toLowerCase()}@chronos.local`,role};return next();}try{const {payload}=await jwtVerify(raw,secret);(req as Request&{user:AuthUser}).user={id:String(payload.sub),name:String(payload.name),email:'',role:payload.role as AuthUser['role'],departmentId:payload.departmentId?String(payload.departmentId):undefined};next();}catch{return res.status(401).json({error:{code:'INVALID_TOKEN',message:'The session is invalid or expired'}});}}
export function currentUser(req:Request){return (req as Request&{user:AuthUser}).user;}
export function authorize(...roles:AuthUser['role'][]){return(req:Request,res:Response,next:NextFunction)=>roles.includes(currentUser(req).role)?next():res.status(403).json({error:{code:'FORBIDDEN',message:`This action requires ${roles.join(' or ')} permission`}});}
