import type {Assignment, Faculty, Policy, Resource, Session, Slot, SolverInput, SolverResult, ValidationReport} from '@chronos/domain';
export type Entity={id:string;[key:string]:unknown};
const days=[['mon','Monday'],['tue','Tuesday'],['wed','Wednesday'],['thu','Thursday'],['fri','Friday']];
const periods=[['09:00','10:00'],['10:00','11:00'],['11:15','12:15'],['12:15','13:15'],['14:00','15:00'],['15:00','16:00']];
export const slots:Slot[]=days.flatMap(([dayId,day],d)=>periods.map(([start,end],index)=>({id:`${dayId}-${index+1}`,dayId,index,label:`${day} P${index+1}`,start,end,isBreak:false})));
export const academicYears:Entity[]=[{id:'ay-26',name:'2026–27',startsOn:'2026-07-01',endsOn:'2027-06-30',active:true}];
export const departments:Entity[]=[{id:'dept-it',code:'IT',name:'Information Technology'},{id:'dept-cse',code:'CSE',name:'Computer Science'}];
export const programs:Entity[]=[{id:'prog-it',code:'BEIT',name:'BE Information Technology',departmentId:'dept-it',academicYearId:'ay-26'}];
export const levels:Entity[]=[{id:'level-3',name:'Third Year',ordinal:3,programId:'prog-it'}];
export const divisions:Entity[]=[{id:'div-a',name:'A',enrollmentCount:60,programLevelId:'level-3'},{id:'div-b',name:'B',enrollmentCount:54,programLevelId:'level-3'}];
export const batches:Entity[]=[{id:'batch-a1',name:'A1',enrollmentCount:30,divisionId:'div-a'},{id:'batch-a2',name:'A2',enrollmentCount:30,divisionId:'div-a'}];
export const faculty:Faculty[]=[{id:'fac-meena',name:'Dr. Meena Rao',departmentId:'dept-it',maxPeriodsPerWeek:18,maxConsecutive:3,unavailableSlotIds:['wed-1','wed-2'],preferredSlotIds:['mon-2','tue-2','thu-2']},{id:'fac-arun',name:'Prof. Arun Shah',departmentId:'dept-it',maxPeriodsPerWeek:20,maxConsecutive:4,unavailableSlotIds:['fri-5','fri-6'],preferredSlotIds:[]}];
export const resources:Resource[]=[{id:'room-201',name:'IT Classroom 201',type:'CLASSROOM',capacity:72,departmentId:'dept-it',buildingId:'main',active:true,capabilities:['Internet','Projector'],unavailableSlotIds:[]},{id:'lab-it-1',name:'IT Computing Lab',type:'LAB',capacity:32,departmentId:'dept-it',buildingId:'tech',active:true,capabilities:['Computers','Internet','Python','SQL'],unavailableSlotIds:['mon-1']},{id:'lab-cse-1',name:'CSE AI Lab',type:'LAB',capacity:36,departmentId:'dept-cse',buildingId:'tech',active:true,capabilities:['Computers','Internet','Python','GPU'],unavailableSlotIds:[]}];
export const enrollments:Entity[]=[];
export const subjects:Entity[]=[{id:'sub-db',code:'IT301',name:'Database Systems',departmentId:'dept-it'},{id:'sub-ml',code:'IT302',name:'Machine Learning',departmentId:'dept-it'}];
export const requirements:Entity[]=[{id:'req-db-lec',subjectId:'sub-db',facultyId:'fac-meena',divisionIds:['div-a'],sessionType:'LECTURE',duration:1,weeklyFrequency:2,resourceType:'CLASSROOM'},{id:'req-db-prac-a1',subjectId:'sub-db',facultyId:'fac-meena',batchIds:['batch-a1'],sessionType:'PRACTICAL',duration:2,weeklyFrequency:1,resourceType:'LAB',requiredCapabilities:['Computers','SQL']},{id:'req-db-prac-a2',subjectId:'sub-db',facultyId:'fac-arun',batchIds:['batch-a2'],sessionType:'PRACTICAL',duration:2,weeklyFrequency:1,resourceType:'LAB',requiredCapabilities:['Computers','SQL']},{id:'req-ml',subjectId:'sub-ml',facultyId:'fac-arun',divisionIds:['div-b'],sessionType:'LECTURE',duration:1,weeklyFrequency:2,resourceType:'CLASSROOM'}];
export const policies:Policy[]=[{id:'pol-it-resources',name:'Prefer IT resources',description:'Use department-owned facilities when eligible',type:'RESOURCE_PREFERENCE',strength:'SOFT',weight:8,scope:{departmentId:'dept-it'},parameters:{preferredResourceIds:['room-201','lab-it-1']},active:true,version:1}];
function divisionAtoms(divisionId:string){const children=batches.filter(b=>b.divisionId===divisionId).map(b=>b.id);return children.length?children:[`division:${divisionId}`];}
export function buildSessions():Session[]{const out:Session[]=[];for(const r of requirements){const subject=subjects.find(s=>s.id===r.subjectId)!;const divisionIds=(r.divisionIds as string[]|undefined)??[];const batchIds=(r.batchIds as string[]|undefined)??[];const atoms=[...new Set([...divisionIds.flatMap(divisionAtoms),...batchIds])];const count=atoms.reduce((n,id)=>{const batch=batches.find(b=>b.id===id);if(batch)return n+Number(batch.enrollmentCount);const divisionId=id.startsWith('division:')?id.slice(9):id;return n+Number(divisions.find(d=>d.id===divisionId)?.enrollmentCount??0);},0);for(let occurrence=1;occurrence<=Number(r.weeklyFrequency);occurrence++)out.push({id:`${r.id}-${occurrence}`,requirementId:r.id,subjectCode:String(subject.code),title:`${subject.name} ${String(r.sessionType).toLowerCase()}`,facultyId:String(r.facultyId),cohortAtomIds:atoms,participantCount:count,duration:Number(r.duration),sessionType:r.sessionType as Session['sessionType'],resourceType:r.resourceType as Session['resourceType'],requiredCapabilities:(r.requiredCapabilities as string[]|undefined)??[],preferredCapabilities:(r.preferredCapabilities as string[]|undefined)??[],preferredDepartmentId:String(subject.departmentId)});}return out;}
export interface Version {id:string;version:number;status:'DRAFT'|'GENERATED'|'VALIDATED'|'REVIEWED'|'APPROVED'|'PUBLISHED';assignments:Assignment[];validation?:ValidationReport;createdAt:string;}
export interface Run {id:string;status:string;startedAt:string;completedAt?:string;result?:SolverResult;}
export const versions:Version[]=[]; export const runs:Run[]=[];
export const collections:Record<string,Entity[]>={departments,programs,levels,divisions,batches,enrollments,subjects,requirements,resources:resources as unknown as Entity[],faculty:faculty as unknown as Entity[],policies:policies as unknown as Entity[]};
export function solverInput():SolverInput{return {slots,resources,faculty,sessions:buildSessions(),policies,timeLimitSeconds:15};}
