-- Campus Chronos initial PostgreSQL schema. PostgreSQL 14+.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE "Role" AS ENUM ('ADMIN','HOD','FACULTY','STUDENT');
CREATE TYPE "ResourceType" AS ENUM ('CLASSROOM','LAB','WORKSHOP','SEMINAR_HALL','AUDITORIUM');
CREATE TYPE "SessionType" AS ENUM ('LECTURE','PRACTICAL','TUTORIAL','WORKSHOP','SEMINAR');
CREATE TYPE "AvailabilityKind" AS ENUM ('AVAILABLE','UNAVAILABLE','PREFERRED','AVOID');
CREATE TYPE "RuleStrength" AS ENUM ('HARD','SOFT');
CREATE TYPE "TimetableStatus" AS ENUM ('DRAFT','GENERATED','VALIDATED','REVIEWED','APPROVED','PUBLISHED','ARCHIVED');
CREATE TYPE "RunStatus" AS ENUM ('QUEUED','BUILDING_CANDIDATES','SOLVING','VALIDATING','SUCCEEDED','INFEASIBLE','FAILED');

CREATE TABLE "AcademicYear" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"name" text NOT NULL UNIQUE,"startsOn" timestamptz NOT NULL,"endsOn" timestamptz NOT NULL,"active" boolean NOT NULL DEFAULT true,"createdAt" timestamptz NOT NULL DEFAULT now(),"updatedAt" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "Department" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"code" text NOT NULL UNIQUE,"name" text NOT NULL UNIQUE,"active" boolean NOT NULL DEFAULT true,"createdAt" timestamptz NOT NULL DEFAULT now(),"updatedAt" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "User" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"email" text NOT NULL UNIQUE,"passwordHash" text,"name" text NOT NULL,"role" "Role" NOT NULL DEFAULT 'STUDENT',"departmentId" text REFERENCES "Department"("id"),"createdAt" timestamptz NOT NULL DEFAULT now(),"updatedAt" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "Program" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"code" text NOT NULL,"name" text NOT NULL,"departmentId" text NOT NULL REFERENCES "Department"("id"),"academicYearId" text NOT NULL REFERENCES "AcademicYear"("id"),UNIQUE("academicYearId","code")); CREATE INDEX "Program_departmentId_idx" ON "Program"("departmentId");
CREATE TABLE "AcademicLevel" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"name" text NOT NULL,"ordinal" integer NOT NULL,"programId" text NOT NULL REFERENCES "Program"("id") ON DELETE CASCADE,UNIQUE("programId","ordinal"));
CREATE TABLE "Division" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"name" text NOT NULL,"enrollmentCount" integer NOT NULL CHECK("enrollmentCount">=0),"programLevelId" text NOT NULL REFERENCES "AcademicLevel"("id") ON DELETE CASCADE,UNIQUE("programLevelId","name"));
CREATE TABLE "Batch" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"name" text NOT NULL,"enrollmentCount" integer NOT NULL CHECK("enrollmentCount">=0),"divisionId" text NOT NULL REFERENCES "Division"("id") ON DELETE CASCADE,UNIQUE("divisionId","name"));
CREATE TABLE "Student" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"rollNumber" text NOT NULL UNIQUE,"name" text NOT NULL);
CREATE TABLE "Enrollment" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"studentId" text NOT NULL REFERENCES "Student"("id"),"divisionId" text NOT NULL REFERENCES "Division"("id"),"batchId" text REFERENCES "Batch"("id"),"validFrom" timestamptz NOT NULL,"validTo" timestamptz,UNIQUE("studentId","divisionId","validFrom")); CREATE INDEX "Enrollment_cohort_idx" ON "Enrollment"("divisionId","batchId");

CREATE TABLE "Faculty" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"employeeCode" text NOT NULL UNIQUE,"name" text NOT NULL,"email" text NOT NULL UNIQUE,"departmentId" text NOT NULL REFERENCES "Department"("id"),"userId" text UNIQUE REFERENCES "User"("id"),"active" boolean NOT NULL DEFAULT true,"maxPeriodsPerWeek" integer,"maxConsecutivePeriods" integer,"createdAt" timestamptz NOT NULL DEFAULT now(),"updatedAt" timestamptz NOT NULL DEFAULT now(),CHECK("maxPeriodsPerWeek" IS NULL OR "maxPeriodsPerWeek">0),CHECK("maxConsecutivePeriods" IS NULL OR "maxConsecutivePeriods">0));
CREATE TABLE "Subject" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"code" text NOT NULL,"name" text NOT NULL,"departmentId" text NOT NULL REFERENCES "Department"("id"),"programId" text REFERENCES "Program"("id"),"academicLevelId" text REFERENCES "AcademicLevel"("id"),"semester" integer,"active" boolean NOT NULL DEFAULT true,UNIQUE("departmentId","code"));
CREATE TABLE "FacultySubjectEligibility" ("facultyId" text NOT NULL REFERENCES "Faculty"("id") ON DELETE CASCADE,"subjectId" text NOT NULL REFERENCES "Subject"("id") ON DELETE CASCADE,"sessionType" "SessionType","active" boolean NOT NULL DEFAULT true,PRIMARY KEY("facultyId","subjectId"));
CREATE TABLE "FacultyPreference" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"facultyId" text NOT NULL REFERENCES "Faculty"("id") ON DELETE CASCADE,"type" text NOT NULL,"weight" integer NOT NULL DEFAULT 10,"parameters" jsonb NOT NULL,"active" boolean NOT NULL DEFAULT true);

CREATE TABLE "Building" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"code" text NOT NULL UNIQUE,"name" text NOT NULL,"active" boolean NOT NULL DEFAULT true);
CREATE TABLE "Floor" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"name" text NOT NULL,"ordinal" integer NOT NULL,"buildingId" text NOT NULL REFERENCES "Building"("id") ON DELETE CASCADE,UNIQUE("buildingId","ordinal"));
CREATE TABLE "Zone" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"name" text NOT NULL,"floorId" text NOT NULL REFERENCES "Floor"("id"),"departmentId" text REFERENCES "Department"("id"),UNIQUE("floorId","name"));
CREATE TABLE "Resource" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"code" text NOT NULL UNIQUE,"name" text NOT NULL,"type" "ResourceType" NOT NULL,"capacity" integer NOT NULL CHECK("capacity">0),"active" boolean NOT NULL DEFAULT true,"departmentId" text REFERENCES "Department"("id"),"floorId" text REFERENCES "Floor"("id"),"zoneId" text REFERENCES "Zone"("id"),"createdAt" timestamptz NOT NULL DEFAULT now(),"updatedAt" timestamptz NOT NULL DEFAULT now()); CREATE INDEX "Resource_eligibility_idx" ON "Resource"("type","active","capacity");
CREATE TABLE "Capability" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"key" text NOT NULL UNIQUE,"name" text NOT NULL);
CREATE TABLE "ResourceCapability" ("resourceId" text NOT NULL REFERENCES "Resource"("id") ON DELETE CASCADE,"capabilityId" text NOT NULL REFERENCES "Capability"("id"),PRIMARY KEY("resourceId","capabilityId"));

CREATE TABLE "ScheduleProfile" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"name" text NOT NULL,"academicYearId" text NOT NULL REFERENCES "AcademicYear"("id"),"active" boolean NOT NULL DEFAULT true,UNIQUE("academicYearId","name"));
CREATE TABLE "WorkingDay" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"profileId" text NOT NULL REFERENCES "ScheduleProfile"("id") ON DELETE CASCADE,"name" text NOT NULL,"ordinal" integer NOT NULL,"enabled" boolean NOT NULL DEFAULT true,UNIQUE("profileId","ordinal"));
CREATE TABLE "TimeSlot" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"workingDayId" text NOT NULL REFERENCES "WorkingDay"("id") ON DELETE CASCADE,"index" integer NOT NULL,"label" text NOT NULL,"startsAt" text NOT NULL,"endsAt" text NOT NULL,"isBreak" boolean NOT NULL DEFAULT false,UNIQUE("workingDayId","index"));
CREATE TABLE "FacultyAvailability" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"facultyId" text NOT NULL REFERENCES "Faculty"("id") ON DELETE CASCADE,"workingDayId" text NOT NULL REFERENCES "WorkingDay"("id"),"timeSlotId" text REFERENCES "TimeSlot"("id"),"kind" "AvailabilityKind" NOT NULL,"reason" text); CREATE INDEX "FacultyAvailability_lookup_idx" ON "FacultyAvailability"("facultyId","workingDayId");
CREATE TABLE "ResourceAvailability" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"resourceId" text NOT NULL REFERENCES "Resource"("id") ON DELETE CASCADE,"workingDayId" text NOT NULL REFERENCES "WorkingDay"("id"),"timeSlotId" text REFERENCES "TimeSlot"("id"),"kind" "AvailabilityKind" NOT NULL,"reason" text);

CREATE TABLE "TeachingRequirement" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"subjectId" text NOT NULL REFERENCES "Subject"("id"),"facultyId" text NOT NULL REFERENCES "Faculty"("id"),"sessionType" "SessionType" NOT NULL,"durationPeriods" integer NOT NULL CHECK("durationPeriods">0),"weeklyFrequency" integer NOT NULL CHECK("weeklyFrequency">0),"resourceType" "ResourceType" NOT NULL,"minCapacity" integer,"requiredResourceId" text REFERENCES "Resource"("id"),"active" boolean NOT NULL DEFAULT true,"preferences" jsonb,"createdAt" timestamptz NOT NULL DEFAULT now(),"updatedAt" timestamptz NOT NULL DEFAULT now()); CREATE INDEX "TeachingRequirement_subject_faculty_idx" ON "TeachingRequirement"("subjectId","facultyId");
CREATE TABLE "RequirementCohort" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"requirementId" text NOT NULL REFERENCES "TeachingRequirement"("id") ON DELETE CASCADE,"divisionId" text REFERENCES "Division"("id"),"batchId" text REFERENCES "Batch"("id"),CHECK(("divisionId" IS NOT NULL) <> ("batchId" IS NOT NULL))); CREATE UNIQUE INDEX "RequirementCohort_unique" ON "RequirementCohort"("requirementId",COALESCE("divisionId",''),COALESCE("batchId",''));
CREATE TABLE "RequirementCapability" ("requirementId" text NOT NULL REFERENCES "TeachingRequirement"("id") ON DELETE CASCADE,"capabilityId" text NOT NULL REFERENCES "Capability"("id"),"required" boolean NOT NULL DEFAULT true,"weight" integer NOT NULL DEFAULT 5,PRIMARY KEY("requirementId","capabilityId"));
CREATE TABLE "SchedulingPolicy" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"name" text NOT NULL,"description" text NOT NULL,"ruleType" text NOT NULL,"strength" "RuleStrength" NOT NULL,"priority" integer NOT NULL DEFAULT 10,"scope" jsonb NOT NULL,"parameters" jsonb NOT NULL,"active" boolean NOT NULL DEFAULT true,"version" integer NOT NULL DEFAULT 1,"effectiveFrom" timestamptz,"effectiveTo" timestamptz,"createdById" text,"createdAt" timestamptz NOT NULL DEFAULT now(),"updatedAt" timestamptz NOT NULL DEFAULT now()); CREATE INDEX "SchedulingPolicy_active_type_idx" ON "SchedulingPolicy"("active","ruleType");

CREATE TABLE "SchedulableSession" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"requirementId" text NOT NULL REFERENCES "TeachingRequirement"("id"),"occurrence" integer NOT NULL,"durationPeriods" integer NOT NULL,"fingerprint" text NOT NULL UNIQUE,UNIQUE("requirementId","occurrence"));
CREATE TABLE "Timetable" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"name" text NOT NULL,"academicYearId" text NOT NULL REFERENCES "AcademicYear"("id"),"profileId" text NOT NULL REFERENCES "ScheduleProfile"("id"),"createdAt" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "TimetableVersion" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"timetableId" text NOT NULL REFERENCES "Timetable"("id") ON DELETE CASCADE,"version" integer NOT NULL,"status" "TimetableStatus" NOT NULL DEFAULT 'DRAFT',"parentVersionId" text REFERENCES "TimetableVersion"("id"),"publishedAt" timestamptz,"approvedById" text REFERENCES "User"("id"),"createdAt" timestamptz NOT NULL DEFAULT now(),"updatedAt" timestamptz NOT NULL DEFAULT now(),UNIQUE("timetableId","version")); CREATE INDEX "TimetableVersion_status_idx" ON "TimetableVersion"("status");
CREATE TABLE "TimetableEntry" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"versionId" text NOT NULL REFERENCES "TimetableVersion"("id") ON DELETE CASCADE,"sessionId" text NOT NULL REFERENCES "SchedulableSession"("id"),"resourceId" text NOT NULL REFERENCES "Resource"("id"),"source" text NOT NULL DEFAULT 'SOLVER',"locked" boolean NOT NULL DEFAULT false,UNIQUE("versionId","sessionId")); CREATE INDEX "TimetableEntry_resource_idx" ON "TimetableEntry"("resourceId");
CREATE TABLE "TimetableEntrySlot" ("entryId" text NOT NULL REFERENCES "TimetableEntry"("id") ON DELETE CASCADE,"timeSlotId" text NOT NULL REFERENCES "TimeSlot"("id"),"ordinal" integer NOT NULL,PRIMARY KEY("entryId","timeSlotId")); CREATE INDEX "TimetableEntrySlot_slot_idx" ON "TimetableEntrySlot"("timeSlotId");
CREATE TABLE "GenerationRun" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"versionId" text REFERENCES "TimetableVersion"("id"),"status" "RunStatus" NOT NULL DEFAULT 'QUEUED',"scope" jsonb,"sessionCount" integer NOT NULL DEFAULT 0,"candidateCount" integer NOT NULL DEFAULT 0,"solverStatus" text,"solverDurationMs" integer,"objectiveMetrics" jsonb,"diagnostics" jsonb,"startedAt" timestamptz NOT NULL DEFAULT now(),"completedAt" timestamptz);
CREATE TABLE "ValidationResult" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"versionId" text NOT NULL REFERENCES "TimetableVersion"("id") ON DELETE CASCADE,"valid" boolean NOT NULL,"metrics" jsonb NOT NULL,"checkedAt" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "Conflict" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"validationId" text NOT NULL REFERENCES "ValidationResult"("id") ON DELETE CASCADE,"code" text NOT NULL,"severity" text NOT NULL,"message" text NOT NULL,"evidence" jsonb,"sessionIds" text[] NOT NULL,"resolvedAt" timestamptz); CREATE INDEX "Conflict_code_idx" ON "Conflict"("code");

CREATE TABLE "Conversation" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"userId" text NOT NULL REFERENCES "User"("id"),"title" text,"createdAt" timestamptz NOT NULL DEFAULT now(),"updatedAt" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "ConversationMessage" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"conversationId" text NOT NULL REFERENCES "Conversation"("id") ON DELETE CASCADE,"role" text NOT NULL,"content" text NOT NULL,"createdAt" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "AIAction" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"conversationId" text NOT NULL REFERENCES "Conversation"("id") ON DELETE CASCADE,"tool" text NOT NULL,"arguments" jsonb NOT NULL,"result" jsonb,"status" text NOT NULL,"confirmationRequired" boolean NOT NULL DEFAULT false,"confirmedAt" timestamptz,"createdAt" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "AuditEvent" ("id" text PRIMARY KEY DEFAULT gen_random_uuid()::text,"actorId" text REFERENCES "User"("id"),"action" text NOT NULL,"entityType" text NOT NULL,"entityId" text,"before" jsonb,"after" jsonb,"ipAddress" text,"createdAt" timestamptz NOT NULL DEFAULT now()); CREATE INDEX "AuditEvent_entity_idx" ON "AuditEvent"("entityType","entityId");
